

version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: echo "hello world 1" # ru
workflows:
  version: 2
  default:
    jobs:
      - build
           
   


