

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.11
    steps:
      - run: echo "hello world 1"
      - run: go get -v github.com/bep/s3deploy
workflows:
  version: 2
  default:
    jobs:
      - build
           
   


