version: 2
jobs:
  build:
    docker:
    - image: circleci/android:api-25-alpha
    working_directory: ~/project
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Chmod permissions
        command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: git config core.autocrlf false
        command: ./gradlew androidDependencies
    - run:
        name: Run Tests
        command: ./gradlew assembleJoyride
    - store_artifacts:
        path: app/build/outputs/apk/release/
        destination: release
    - run:
        name: Upload to Slack
        command: |
          export GIT_COMMIT_DESC=$(git log --format=oneline -n 1 | sed -E 's/^[^ ]+ (.*)$/\1/g')
          curl -F file=@app/build/outputs/apk/release/operator.apk -F channels=autorelease -F token=$SLACK_API_TOKEN -F title=Operatorapp  https://slack.com/api/files.upload
    - run:
        name: Upload to Alpha
        command: ./gradlew publishApk
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/joyridedev/operatorapp/compare/9e42725e28bdbb7a4b5838b49c69f42217ca73f7...e80e18cad9e22c1c3c35d11dd624396b0baf34d2
workflows:
  version: 2
  workflow:
    jobs:
    - build
      
      
