

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: echo "hello world 1"
#       - run: go get -v github.com/bep/s3deploy
      - run: echo `git log --pretty=format:'%Cred%h%Creset - %s %C(bold blue)[%an]%Creset'`
      - run: echo 'export MESSAGE=/git log --pretty=format:'%Cred%h%Creset - %s %C(bold blue)[%an]%Creset' >> $BASH_ENV
      - run : echo $MESSAGE
workflows:
  version: 2
  default:
    jobs:
      - build
           
   


