version: 2.1


parameters:
  action:
    type: enum
    enum: [build, report]
    default: build

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run: echo "build"
  pretest:
    docker:
      - image: circleci/node
    steps:
      - run: echo "pretest"
      - run: netstat -tunlp
#       - run: 
#           command: |
#             test:
#               p: 4
  test:
    parameters:
      p:
        type: integer
        default: 2
        
    docker:
      - image: circleci/node    
    parallelism: << parameters.p >>
    steps:
      - run: echo "test"

      
      - run: echo << pipeline.git.branch >>
#       - run:  
#           command: |
#             if [ << pipeline.git.branch >> = master ]; then
#                echo << parameters.p >> = 2
#             else  
#               echo << parameters.p >> = 4
#             fi
      - run:  
          command: |
            if [ << pipeline.parameters.action >> = build ]; then
               echo << parameters.p >> = 2
            else  
              echo << parameters.p >> = 4
            fi
      - run : echo << parameters.p >>      
workflows:
  first_workflow:
    when:
      equal: [ build, << pipeline.parameters.action >> ]
    jobs:
      - build:
          filters:
            branches:
              ignore :
                - master
#       - pretest        
      - test:
          requires:
            - build
  second_workflow:
    when:
      not: 
        equal: [ /develop.*/,  << pipeline.git.branch >> ]
    jobs:
      - build
#           filters:
#             branches:
#               only:
#                 - /develop.*/
      - pretest
      - test:
          requires:
            - build
#test
