jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "build"
  test:
    docker:
      - image: circleci/node
    parameters:
      parallelism:
        type: integer
        default: 2
    parallelism: << parameters.parallelism >>
    steps:
      - checkout
      - run: echo "test"
      - run : echo << parameters.parallelism >>
workflows:
  version: 2
  first_workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - test:
          requires:
            - build
  second_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
          parallelism: 4
            - build

       
