version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update

      - run:
          name: Build App Bundle
          command: msbuild SimpleFreeCell\SimpleFreeCell.UWP\SimpleFreeCell.UWP.csproj /p:Configuration=Release /p:AppxBundle=Always /p:AppxBundlePlatforms="x86|x64|ARM" /p:BuildAppxUploadPackageForUap=true /p:UapAppxPackageBuildMode=StoreUpload /p:PackageCertificatePassword="testpassword" -restore      
      - run:
          name: Compress AppPackages
          command: Compress-Archive -Path ./SimpleFreeCell/SimpleFreeCell.UWP/AppPackages -DestinationPath ./AppPackages.zip
      - store_artifacts:
          path: ./AppPackages.zip
          resource_class: windows.medium
          shell: powershell.exe -ExecutionPolicy Bypass
      
      
