jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run: echo "Hello World" 
      - slack/notify:
          color: '#42e2f4'
          message: 'Hello from CircleCI to Slack :)'
          webhook: 'T02519B3Z/B011ZSJHZSA/5cqYrZL3RovWfGpL5yai6kdC'
orbs:
  slack: circleci/slack@3.4.2
version: 2.1
workflows:
  your-workflow:
    jobs:
      - build
      
      
