version: 2.1
orbs:
  queue: eddiewebb/queue@1.5.0

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "build"
  pretest:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "pretest"
  test:
    parameters:
      p:
        type: integer
        default: 1
    docker:
      - image: circleci/node    
    parallelism: << parameters.p >>
    steps:
      - queue/until_front_of_line:
          only-on-branch: master
          time: '10'
      - checkout
      - run: echo "test"
      - run : echo << parameters.p >>
workflows:
  first_workflow:
    jobs:
#       - queue/block_workflow:
      - build:
          filters:
            branches:
              only:
                - develop
      - test:
          filters:
            branches:
              only:
                - develop
          requires:
            - build
  second_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - pretest
      - test:
#           requires:
#             - queue/block_workflow
          filters:
            branches:
              only:
                - master
          
          p: 3
          requires:
            - build
       
