version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  test:
    executor:
      name: node/default
    environment:
      PUBLIC_URL: https://boost-ui.s3-us-west-2.amazonaws.com/<< pipeline.git.branch >>
      REACT_APP_BOOST_API_BASE_PATH: "/api"
      REACT_APP_BASE_PATH: "/v2/app"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "//npm.pkg.github.com/:_authToken=$GITHUB_PACKAGE_TOKEN" >> .npmrc
            - run: npm install
            - run: npm test
            
workflows:
  test:
    jobs:
      - test:
          context: github_packages
          filters:
            branches:
              only:
                - /stage-.*/    
