version: 2.1

jobs:
  rails_test:
    parameters:
      parallelism:
        type: integer
        default: 2
    executor: ruby-executor
    parallelism: << parameters.parallelism >>
    

workflows:
  version: 2.1
  develop_workflow:
    jobs:
      - rails_build:
          filters:
            branches:
              ignore:
                - master
      - rails_test:
          requires:
            - rails_build
  production_workflow:
    jobs:
      - rails_build:
          filters:
            branches:
              only: master
      - rails_test:
          parallelism: 4
          requires:
            - rails_build

       
