
#test
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: echo "hello world 1"
#       - run: go get -v github.com/bep/s3deploy
#       - run: echo `git log --pretty=format:'%Cred%h%Creset - %s %C(bold blue)[%an]%Creset'`
#       - run: echo 'export MESSAGE=git log --pretty=format:'%Cred%h%Creset - %s %C[%an]%Creset' >> $BASH_ENV
      - run : echo "hiiii"
      - run : sleep 20 
  test1:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: echo "test 1"

  test2:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: echo "test2"  
      
workflows:
  version: 2
  default:
    jobs:
      - build
      - test1
      - test2
      
      
      #test 
           
           
           #
   


