version: 2.1

jobs:
  rails_test:
    docker:
        - image: circleci/node
    parameters:
      parallelism:
        type: integer
        default: 2
      
    parallelism: << parameters.parallelism >>
    steps: 
      - run : echo << parameters.parallelism >>
      
      
  rails_build:
    docker:
        - image: circleci/node
     steps: 
      - run: echo "rails build" 
    
    

workflows:
  version: 2.1
  develop_workflow:
    jobs:
      - rails_build:
          filters:
            branches:
              ignore:
                - master
      - rails_test:
          requires:
            - rails_build
  production_workflow:
    jobs:
      - rails_build:
          filters:
            branches:
              only: master
      - rails_test:
          parallelism: 4
          requires:
            - rails_build

       
