jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "build"
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "test"
workflows:
  version: 2
  first_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
  second_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build

       
