version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    environment:
      NODE_ENV: circleci
    steps:
      - run: npm run test
  
  deploy_github_package:
    parameters:
      directory:
        type: string
      packagename:
        type: string
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    environment:
      NODE_ENV: circleci
    steps:
      - run: |
          echo "hello world"
#       - checkout:
#           path: ~/repo
#       - run: |
#           ./bash/isLocalGreaterThanLatestVersion.sh ${GITHUB_PAT} ${GITHUB_ORG} << parameters.packagename >> << parameters.directory >>
#       - run: |
#           cd << parameters.directory >> && npm ci
#       - run: |
#           echo export GITHUB_REGISTRY=${GITHUB_PACKAGES_URL}${GITHUB_ORG} >> $BASH_ENV
#           echo export GITHUB_ORG=@${GITHUB_ORG} >> $BASH_ENV
#           echo export npm_config_repository_type=git >> $BASH_ENV
#           echo export npm_config_repository_url=${GITHUB_LIBRARY_REPO} >> $BASH_ENV
#           echo export npm_config_publishConfig_registry=${GITHUB_PACKAGES_URL}>> $BASH_ENV
#           echo export npm_config_author=psn >> $BASH_ENV
#       - run: |
#           echo "//npm.pkg.github.com/:_authToken=${GITHUB_PAT}" > ~/.npmrc
#           cd << parameters.directory >> && npm publish
      
workflows:
  version: 2
  test:
    jobs:
      - deploy_github_package:
          name: deploy google-bigquery-service
          directory: ./services/GoogleBigQueryService/
          packagename: google-bigquery-service
          filters:
            branches:
              only:
                - initial
                - master
      - deploy_github_package:
          name: deploy google-storage-service
          directory: ./services/GoogleStorageService/
          packagename: google-storage-service
          filters:
            branches:
              only:
                - initial
                - master
