version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "build"
  pretest:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "pretest"
  test:
    parameters:
      p:
        type: integer
        default: 2
        
    docker:
      - image: circleci/node    
    parallelism: << parameters.p >>
    steps:
      - checkout
      - run: echo "test"
      
      - run: echo << pipeline.git.branch >>
#       - run:  if [ << pipeline.git.branch >> = master ]; then
#                echo "this is the MASTER BRANCH!!!"
#             fi
      - run:  
          command: |
            if [ << pipeline.git.branch >> = master ]; then
               echo << parameters.p >> = 2
            else  
              echo << parameters.p >> = 4
            fi

      - run : echo << parameters.p >>      
workflows:
  first_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - test:
          filters:
            branches:
              only:
                - develop
          requires:
            - build
  second_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - pretest
      - test:
          filters:
            branches:
              only:
                - master
          

          requires:
            - build
