version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  step1:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo "hello world"
  
workflows:
    build:
      jobs:
        - build:
            type: approval
        - step1
       
