# # jobs:
# #   build:
# #     docker:
# #       - image: circleci/node
# #     steps:
# #       - run: echo "Hello World" 
# #       - slack/notify:
# #           color: '#42e2f4'
# #           message: 'Hello from CircleCI to Slack :)'
# #           webhook: '${SLACK_WEBHOOK}'
# # orbs:
# #   slack: circleci/slack@3.4.2
# # version: 2.1
# # workflows:
# #   your-workflow:
# #     jobs:
# #       - build
      
      
      
# # version: 2.1
# # jobs:
# #   tag_calver:
# #     docker:
# #       - image: circleci/python:3.6.5
# #     steps:
# #        - run:
# #           name: Set up make and lint
# #           command: |
# #             virtualenv venv
# #             . venv/bin/activate
# #             # TODO: bake node into image instead of downloading every time
# #             # https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
# #             curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
# #             sudo apt-get install -y nodejs
# #             pip install --upgrade pip
        
# #             make install


# # workflows:
# #   tag_workflow:
# #     jobs:
# #       - tag_calver

      
# jobs:
#   build:
#     docker:
#       - image: circleci/node
#     steps:
#       - run: echo "Hello World" 
     
# version: 2.1
# workflows:
#   your-workflow:
#     jobs:
#       - build
      
# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node>
#     steps:
#       - checkout
#       - run: echo "build step "
#   test:
#     tyoe: approval
#     steps:
#       - checkout
#       - run: echo "test step "
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test
version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "build step "
  test:
    type: approval
    docker:
        - image: circleci/node
    # tyoe: approval
    steps:
      - checkout
      - run: echo "test step "
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
            type: approval
        
