

version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node
#       - image: circleci/ruby:2.5.1-node-browsers
#     parallelism: 6
    steps:
      - run: echo "hello world 1" # ru
      - run: echo "testing my messy code for a jira" # ru

