version: 2.1

executors: # a reusable executor
  ruby-executor:
    docker:
      - image: circleci/ruby

jobs:
  rails_test:
    executor: ruby-executor
    steps: 
#       - run : echo << parameters.parallelism >>
      - run : echo "rails_test" 
#     parameters:
#       parallelism:
#         type: integer
#         default: 2
        
#     executor: ruby-executor  
#     parallelism: << parameters.parallelism >>
#     steps: 
# #       - run : echo << parameters.parallelism >>
#       - run : echo "rails_test" 
      
      
  rails_build:
    executor: ruby-executor
    steps: 
#       - run : echo << parameters.parallelism >>
      - run : echo "rails_build" 
    
    

workflows:
  version: 2.1
  develop_workflow:
    jobs:
      - rails_build:
#           filters:
#             branches:
#               ignore:
#                 - master
      - rails_test:
          requires:
            - rails_build
  production_workflow:
    jobs:
      - rails_build:
#           filters:
#             branches:
#               only: master
      - rails_test:
#           parallelism: 4
          requires:
            - rails_build

       
