version: 2 
jobs:
    test:
      docker:
        - image: circleci/node
     
  
      steps:
          - run: echo "hello 1"
          - run: echo "hello 2"
          - run: echo "hello 3"
          - run: echo "hello 4"
          - run: sudo npm install
          - run: npm install
# 
workflows:
    version: 2
    build&test: 
        jobs:
            - test
