version: 2.1

workflows:
  main:
    jobs:
      - deploy:
          filters:
            tags:
              only: /production-.*/
            branches:
              ignore: /.*/
          environment: << pipeline.git.tag >>

jobs:
  deploy:
    docker:
    - image: circleci/node
    parameters:
      environment:
        type: string
        default: ''
        
    steps:
      - run: some-command << parameters.environment >>
